-- Generated by load_3nf.py -- do not edit by hand.
-- Run AFTER schema_3nf.sql:
--   mysql -u <user> -p --local-infile=1 < load_3nf.sql
-- If the server has local_infile OFF, enable it for the session with
--   SET GLOBAL local_infile = 1;   (needs SUPER/SYSTEM_VARIABLES_ADMIN)

USE RentBoardDB;
SET FOREIGN_KEY_CHECKS = 0;
SET UNIQUE_CHECKS = 0;

-- 41 rows
LOAD DATA LOCAL INFILE '/Users/junyanhuang/Documents/GitHub/Data_201/house/load/neighborhood.tsv'
    INTO TABLE neighborhood
    FIELDS TERMINATED BY '\t' ESCAPED BY '\\'
    LINES TERMINATED BY '\n'
    (neighborhood_id, name);

-- 13,435 rows
LOAD DATA LOCAL INFILE '/Users/junyanhuang/Documents/GitHub/Data_201/house/load/location_point.tsv'
    INTO TABLE location_point
    FIELDS TERMINATED BY '\t' ESCAPED BY '\\'
    LINES TERMINATED BY '\n'
    (point_id, longitude, latitude, neighborhood_id, district_id);

-- 4,287 rows
LOAD DATA LOCAL INFILE '/Users/junyanhuang/Documents/GitHub/Data_201/house/load/assessor_block.tsv'
    INTO TABLE assessor_block
    FIELDS TERMINATED BY '\t' ESCAPED BY '\\'
    LINES TERMINATED BY '\n'
    (block_num);

-- 7,677 rows
LOAD DATA LOCAL INFILE '/Users/junyanhuang/Documents/GitHub/Data_201/house/load/street_block.tsv'
    INTO TABLE street_block
    FIELDS TERMINATED BY '\t' ESCAPED BY '\\'
    LINES TERMINATED BY '\n'
    (street_block_id, raw_label, block_range, street_name);

-- 45 rows
LOAD DATA LOCAL INFILE '/Users/junyanhuang/Documents/GitHub/Data_201/house/load/bedroom_type.tsv'
    INTO TABLE bedroom_type
    FIELDS TERMINATED BY '\t' ESCAPED BY '\\'
    LINES TERMINATED BY '\n'
    (bedroom_type_id, raw_label, bedrooms, is_unparseable);

-- 31 rows
LOAD DATA LOCAL INFILE '/Users/junyanhuang/Documents/GitHub/Data_201/house/load/bathroom_type.tsv'
    INTO TABLE bathroom_type
    FIELDS TERMINATED BY '\t' ESCAPED BY '\\'
    LINES TERMINATED BY '\n'
    (bathroom_type_id, raw_label, bathrooms, is_shared, is_unparseable);

-- 21,008 rows
LOAD DATA LOCAL INFILE '/Users/junyanhuang/Documents/GitHub/Data_201/house/load/duplicate_group.tsv'
    INTO TABLE duplicate_group
    FIELDS TERMINATED BY '\t' ESCAPED BY '\\'
    LINES TERMINATED BY '\n'
    (dup_group_id, content_hash, member_count);

-- 550,201 rows
LOAD DATA LOCAL INFILE '/Users/junyanhuang/Documents/GitHub/Data_201/house/load/unit_record.tsv'
    INTO TABLE unit_record
    FIELDS TERMINATED BY '\t' ESCAPED BY '\\'
    LINES TERMINATED BY '\n'
    (unique_id, batch_id, submission_year, signature_date, block_num, street_block_id, point_id, building_unit_count, year_property_built, occupancy_type_id, bedroom_type_id, bathroom_type_id, sqft_band_id, rent_band_id, occupancy_or_vacancy_date, occupancy_or_vacancy_year, date_unknown_reason_id, occupancy_year_raw, vacancy_date, past_occupancy, other_utilities_raw, dup_group_id);

-- 700,285 rows
LOAD DATA LOCAL INFILE '/Users/junyanhuang/Documents/GitHub/Data_201/house/load/record_utility_included.tsv'
    INTO TABLE record_utility_included
    FIELDS TERMINATED BY '\t' ESCAPED BY '\\'
    LINES TERMINATED BY '\n'
    (unique_id, utility_id, from_checkbox, from_other_text);

-- 9,835 rows
LOAD DATA LOCAL INFILE '/Users/junyanhuang/Documents/GitHub/Data_201/house/load/record_quality_flag.tsv'
    INTO TABLE record_quality_flag
    FIELDS TERMINATED BY '\t' ESCAPED BY '\\'
    LINES TERMINATED BY '\n'
    (unique_id, flag_id, rejected_value);

-- 81,004 rows
LOAD DATA LOCAL INFILE '/Users/junyanhuang/Documents/GitHub/Data_201/house/load/occupancy_history.tsv'
    INTO TABLE occupancy_history
    FIELDS TERMINATED BY '\t' ESCAPED BY '\\'
    LINES TERMINATED BY '\n'
    (history_id, unique_id, seq_no, date_range_type_id, start_date, end_date);

SET UNIQUE_CHECKS = 1;
SET FOREIGN_KEY_CHECKS = 1;

-- LOAD DATA downgrades a CHECK-constraint failure to a warning and
-- discards the row, so compare every table against what was staged.
-- Every verdict must read 'ok'.
SELECT 'neighborhood' AS table_name, COUNT(*) AS rows_loaded, 41 AS rows_staged, IF(COUNT(*) = 41, 'ok', 'ROWS LOST') AS verdict FROM neighborhood UNION ALL SELECT 'location_point' AS table_name, COUNT(*) AS rows_loaded, 13435 AS rows_staged, IF(COUNT(*) = 13435, 'ok', 'ROWS LOST') AS verdict FROM location_point UNION ALL SELECT 'assessor_block' AS table_name, COUNT(*) AS rows_loaded, 4287 AS rows_staged, IF(COUNT(*) = 4287, 'ok', 'ROWS LOST') AS verdict FROM assessor_block UNION ALL SELECT 'street_block' AS table_name, COUNT(*) AS rows_loaded, 7677 AS rows_staged, IF(COUNT(*) = 7677, 'ok', 'ROWS LOST') AS verdict FROM street_block UNION ALL SELECT 'bedroom_type' AS table_name, COUNT(*) AS rows_loaded, 45 AS rows_staged, IF(COUNT(*) = 45, 'ok', 'ROWS LOST') AS verdict FROM bedroom_type UNION ALL SELECT 'bathroom_type' AS table_name, COUNT(*) AS rows_loaded, 31 AS rows_staged, IF(COUNT(*) = 31, 'ok', 'ROWS LOST') AS verdict FROM bathroom_type UNION ALL SELECT 'duplicate_group' AS table_name, COUNT(*) AS rows_loaded, 21008 AS rows_staged, IF(COUNT(*) = 21008, 'ok', 'ROWS LOST') AS verdict FROM duplicate_group UNION ALL SELECT 'unit_record' AS table_name, COUNT(*) AS rows_loaded, 550201 AS rows_staged, IF(COUNT(*) = 550201, 'ok', 'ROWS LOST') AS verdict FROM unit_record UNION ALL SELECT 'record_utility_included' AS table_name, COUNT(*) AS rows_loaded, 700285 AS rows_staged, IF(COUNT(*) = 700285, 'ok', 'ROWS LOST') AS verdict FROM record_utility_included UNION ALL SELECT 'record_quality_flag' AS table_name, COUNT(*) AS rows_loaded, 9835 AS rows_staged, IF(COUNT(*) = 9835, 'ok', 'ROWS LOST') AS verdict FROM record_quality_flag UNION ALL SELECT 'occupancy_history' AS table_name, COUNT(*) AS rows_loaded, 81004 AS rows_staged, IF(COUNT(*) = 81004, 'ok', 'ROWS LOST') AS verdict FROM occupancy_history;

-- FOREIGN_KEY_CHECKS was off during the bulk load, so prove the
-- references anyway; every row below must be 0.
SELECT 'unit_record -> location_point' AS fk, COUNT(*) AS orphans
  FROM unit_record r LEFT JOIN location_point p USING (point_id)
 WHERE r.point_id IS NOT NULL AND p.point_id IS NULL
UNION ALL
SELECT 'unit_record -> street_block', COUNT(*)
  FROM unit_record r LEFT JOIN street_block s USING (street_block_id)
 WHERE r.street_block_id IS NOT NULL AND s.street_block_id IS NULL
UNION ALL
SELECT 'unit_record -> assessor_block', COUNT(*)
  FROM unit_record r LEFT JOIN assessor_block b USING (block_num)
 WHERE r.block_num IS NOT NULL AND b.block_num IS NULL
UNION ALL
SELECT 'occupancy_history -> unit_record', COUNT(*)
  FROM occupancy_history h LEFT JOIN unit_record r USING (unique_id)
 WHERE r.unique_id IS NULL;
