-- AI-ASSISTANCE DISCLOSURE
-- The initial decision making for this 3NF relational schema was assisted
-- with AI. AI was not simply used to take the CSV and output a 3NF. Instead,
-- it was asked to analyze the contents of each row and explain why certain
-- dependencies that seem reasonable would not work due to the actual contents
-- of each entry. The team will review, understand, verify, and modify this
-- schema before deciding whether to use any part of it in the final project.

DROP DATABASE IF EXISTS sf_rent_board;
CREATE DATABASE sf_rent_board CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;
USE sf_rent_board;

-- ============================================================================
-- Source attribute notes from the project notes
--
-- Building/Property Attributes
--   block_num: block number of the property -> can be the key attribute?
--   block-address: street address of the building block (String)
--   unit_count: total number of residential units in the property (Int)
--   year_property_built: year building was constructed (Year/Int)
--   point: geospatial coordinates for mapping
--   analysis_neighborhood: specific SF neighborhood that the property belongs in
--                          -> possibly useful for subtable
--   supervisor_district: political district (Int) -> useful for storytelling
--
-- Unit Attributes
--   bedroom_count: number of bedrooms in this residential unit (Int)
--   bathroom_count: number of bathrooms in this residential unit (Int)
--   unit_count: total number of residential units in this property (Int)
--   square_footage: square footage of unit
--   block_num: could be a foreign key to connect with building
--
-- Rental Record Attributes
--   unique_id: unique identifier for each submission recorded generated by DataSF
--              -> KEY ATTRIBUTE
--   submission_year: fee year for which the submission is received (Year)
--   case_type_name: name of the submission type (String) -> possibly use to
--                   make subtables
--   occupancy_type: occupancy type reported for this residential unit (String)
--   past_occupancy: occupied in the past (Yes/No)
--   occupancy_or_vacancy_date: year the unit was occupied (?)
--   occupancy_or_vacancy_date_history: log description of occupancy
--   signature_date: date the submission was signed
--   monthly_rent: monthly rent in $250 increments -> important for our project
--                  probably
--   vacancy_date: specific date the unit became empty
--
-- Utilities Attributes
--   base_rent_includes_water_sewer: includes water/sewer (Y/N)
--   base_rent_includes_natural_gas: includes gas (Y/N)
--   base_rent_includes_electricity: includes electricity (Y/N)
--   base_rent_includes_refuse_recycling: include trash (Y/N)
--   base_rent_includes_other_utilities: includes unspecified utilities (Y/N)
--
-- Database attributes / metadata
--   data_as_of: date dataset was published
--   data_loaded_at: timestamp when record was added to the database
--
-- These are the original notes, not final interpretations. The comments below
-- each normalized table explain which notes were retained, transformed, or
-- rejected after checking the data dependencies.
-- ============================================================================

-- ---------------------------------------------------------------------------
-- ExtractBatch
-- The metadata columns describe the dataset extract rather than an individual
-- housing report. They are stored once here for provenance and are not repeated
-- on every UnitReport row. The team may exclude this table in a simpler final
-- schema after documenting that decision.
-- ---------------------------------------------------------------------------
CREATE TABLE ExtractBatch (
  batch_id SMALLINT UNSIGNED PRIMARY KEY,
  data_as_of DATETIME NOT NULL,
  data_loaded_at DATETIME NOT NULL,
  source_filename VARCHAR(255) NOT NULL,
  source_row_count INT UNSIGNED NULL
);

-- ---------------------------------------------------------------------------
-- FilingCycle
-- `submission_year` is the fee year for which the submission is received.
-- `case_type_name` is the name of the submission type. If it is one-to-one
-- with the year, keeping it here avoids repeating it in UnitReport.
-- ---------------------------------------------------------------------------
CREATE TABLE FilingCycle (
  submission_year SMALLINT UNSIGNED PRIMARY KEY,
  case_type_name VARCHAR(100) NOT NULL UNIQUE,
  CHECK (submission_year BETWEEN 2022 AND 2026)
);

-- ---------------------------------------------------------------------------
-- Geographic attributes
-- `analysis_neighborhood` is the specific SF neighborhood that the property
-- belongs in -> possibly useful for subtable. `supervisor_district` is the
-- political district (Int) -> useful for storytelling. `point` is the
-- geospatial coordinate used for mapping.
-- ---------------------------------------------------------------------------
CREATE TABLE Neighborhood (
  neighborhood_id SMALLINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(80) NOT NULL UNIQUE
);

CREATE TABLE SupervisorDistrict (
  district_id TINYINT UNSIGNED PRIMARY KEY,
  CHECK (district_id BETWEEN 1 AND 11)
);

CREATE TABLE LocationPoint (
  point_id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  longitude DECIMAL(12,9) NOT NULL,
  latitude DECIMAL(12,9) NOT NULL,
  neighborhood_id SMALLINT UNSIGNED NULL,
  district_id TINYINT UNSIGNED NULL,
  UNIQUE (longitude, latitude),
  CHECK (longitude BETWEEN -123 AND -122),
  CHECK (latitude BETWEEN 37 AND 38),
  FOREIGN KEY (neighborhood_id) REFERENCES Neighborhood(neighborhood_id),
  FOREIGN KEY (district_id) REFERENCES SupervisorDistrict(district_id)
);

-- ---------------------------------------------------------------------------
-- Building/property labels
-- `block_num` is the block number of the property -> can be the key attribute?
-- `block-address` is the street address of the building block (String).
-- The final design tests these statements instead of assuming block_num is a
-- unique property key.
-- ---------------------------------------------------------------------------
CREATE TABLE AssessorBlock (
  block_num VARCHAR(5) PRIMARY KEY
);

CREATE TABLE BlockAddress (
  block_address_id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  raw_label VARCHAR(120) NOT NULL UNIQUE,
  block_range SMALLINT UNSIGNED NULL,
  street_name VARCHAR(100) NULL
);

-- ---------------------------------------------------------------------------
-- Unit and rental categorical attributes
-- `bedroom_count` is the number of bedrooms in this residential unit (Int).
-- `bathroom_count` is the number of bathrooms in this residential unit (Int).
-- `square_footage` is the square footage of the unit.
-- `occupancy_type` is the occupancy type reported for this residential unit.
--
-- Each lookup stores the raw label (a candidate key) and only the values that
-- cannot be computed from other columns. Flags such as "unparseable" or
-- "no rent paid" are not stored, because they follow from another column of
-- the same row and storing them would be a transitive dependency:
--   unparseable bedroom label     canonical_bedrooms IS NULL
--   unparseable bathroom label    canonical_bathrooms IS NULL AND NOT is_shared
--   unknown square footage        min_sqft IS NULL
--   no rent paid ("$0 ...", "0")  min_rent IS NULL
-- is_shared and overlaps_other cannot be computed from other columns, so they
-- stay.
-- ---------------------------------------------------------------------------
CREATE TABLE OccupancyType (
  occupancy_type_id TINYINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(40) NOT NULL UNIQUE
);

CREATE TABLE BedroomLabel (
  bedroom_label_id SMALLINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  raw_label VARCHAR(40) NOT NULL UNIQUE,
  canonical_bedrooms TINYINT UNSIGNED NULL,
  CHECK (canonical_bedrooms IS NULL OR canonical_bedrooms BETWEEN 0 AND 10)
);

CREATE TABLE BathroomLabel (
  bathroom_label_id SMALLINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  raw_label VARCHAR(80) NOT NULL UNIQUE,
  canonical_bathrooms DECIMAL(3,1) NULL,
  is_shared BOOLEAN NOT NULL DEFAULT FALSE,
  CHECK (canonical_bathrooms IS NULL OR canonical_bathrooms BETWEEN 0 AND 10)
);

CREATE TABLE SquareFootageBand (
  sqft_band_id TINYINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  raw_label VARCHAR(40) NOT NULL UNIQUE,
  min_sqft SMALLINT UNSIGNED NULL,
  max_sqft SMALLINT UNSIGNED NULL,
  CHECK (max_sqft IS NULL OR min_sqft IS NULL OR max_sqft >= min_sqft)
);

CREATE TABLE RentBand (
  rent_band_id TINYINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  raw_label VARCHAR(50) NOT NULL UNIQUE,
  min_rent DECIMAL(8,2) NULL,
  max_rent DECIMAL(8,2) NULL,
  overlaps_other BOOLEAN NOT NULL DEFAULT FALSE,
  CHECK (max_rent IS NULL OR min_rent IS NULL OR max_rent >= min_rent)
);

-- ---------------------------------------------------------------------------
-- UnitReport
-- `past_occupancy` records whether the unit was occupied in the past (Yes/No).
-- `occupancy_or_vacancy_date` records the year/date the unit was occupied (?);
-- the original uncertainty is retained in the project notes and the cleaned
-- schema separates dates, years, and unknown text.
-- `signature_date` is the date the submission was signed.
-- `monthly_rent` is monthly rent in $250 increments -> important for our
-- project probably.
-- `vacancy_date` is the specific date the unit became empty.
-- `unit_count` is the total number of residential units in this property (Int),
-- but remains a reported fact on this row unless a stable property key is
-- demonstrated.
--
-- Move-in timing is stored exactly one way. When a valid date exists, the
-- source year column is derivable from it and is not stored again (storing
-- both would be a transitive dependency: unique_id -> date -> year). At most
-- one of these three columns is populated:
--   occupancy_or_vacancy_date  a valid date
--   occupancy_year             a plausible year with no usable date
--   date_unknown_text          the form's "Year Unknown (...)" answers, or any
--                              other text (for example "20204"); the latter
--                              is also logged in quality_issues.csv
-- other_utilities_raw is the verbatim free-text answer. ReportUtility rows are
-- parsed from it, but no column of this table determines it, so keeping the
-- source text does not break 3NF.
-- The loader guarantees this before staging. LOAD DATA turns a CHECK failure
-- into a warning and skips the row, so the generated load script compares
-- loaded and staged row counts to catch any row that is dropped this way.
-- ---------------------------------------------------------------------------
CREATE TABLE UnitReport (
  -- The notes identify unique_id as the key attribute for each submission.
  unique_id BIGINT NOT NULL PRIMARY KEY,
  batch_id SMALLINT UNSIGNED NOT NULL,
  submission_year SMALLINT UNSIGNED NOT NULL,
  block_num VARCHAR(5) NULL,
  block_address_id INT UNSIGNED NULL,
  point_id INT UNSIGNED NULL,
  reported_unit_count DECIMAL(6,1) NULL,
  year_property_built SMALLINT UNSIGNED NULL,
  occupancy_type_id TINYINT UNSIGNED NOT NULL,
  bedroom_label_id SMALLINT UNSIGNED NULL,
  bathroom_label_id SMALLINT UNSIGNED NULL,
  sqft_band_id TINYINT UNSIGNED NULL,
  rent_band_id TINYINT UNSIGNED NULL,
  occupancy_or_vacancy_date DATE NULL,
  occupancy_year SMALLINT UNSIGNED NULL,
  date_unknown_text VARCHAR(80) NULL,
  vacancy_date DATE NULL,
  past_occupancy BOOLEAN NULL,
  other_utilities_raw VARCHAR(255) NULL,
  signature_date DATE NULL,
  FOREIGN KEY (batch_id) REFERENCES ExtractBatch(batch_id),
  FOREIGN KEY (submission_year) REFERENCES FilingCycle(submission_year),
  FOREIGN KEY (block_num) REFERENCES AssessorBlock(block_num),
  FOREIGN KEY (block_address_id) REFERENCES BlockAddress(block_address_id),
  FOREIGN KEY (point_id) REFERENCES LocationPoint(point_id),
  FOREIGN KEY (occupancy_type_id) REFERENCES OccupancyType(occupancy_type_id),
  FOREIGN KEY (bedroom_label_id) REFERENCES BedroomLabel(bedroom_label_id),
  FOREIGN KEY (bathroom_label_id) REFERENCES BathroomLabel(bathroom_label_id),
  FOREIGN KEY (sqft_band_id) REFERENCES SquareFootageBand(sqft_band_id),
  FOREIGN KEY (rent_band_id) REFERENCES RentBand(rent_band_id),
  CHECK (year_property_built IS NULL OR year_property_built BETWEEN 1800 AND 2030),
  CHECK (occupancy_year IS NULL OR occupancy_year BETWEEN 1900 AND 2026),
  CHECK ((occupancy_or_vacancy_date IS NOT NULL) + (occupancy_year IS NOT NULL)
       + (date_unknown_text IS NOT NULL) <= 1)
);

-- ---------------------------------------------------------------------------
-- Utilities
-- The notes identify four Y/N utility fields and an unspecified-utilities
-- field. The normalized design represents included utilities as rows so a
-- report can have multiple utilities while preserving the original free text.
-- Free text that names no known utility becomes an `other` row, even when a
-- checkbox was also ticked. "none"/"n/a" style answers produce no row.
-- ---------------------------------------------------------------------------
CREATE TABLE Utility (
  utility_id TINYINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(40) NOT NULL UNIQUE
);

CREATE TABLE ReportUtility (
  unique_id BIGINT NOT NULL,
  utility_id TINYINT UNSIGNED NOT NULL,
  source_checkbox BOOLEAN NOT NULL DEFAULT FALSE,
  source_text BOOLEAN NOT NULL DEFAULT FALSE,
  PRIMARY KEY (unique_id, utility_id),
  FOREIGN KEY (unique_id) REFERENCES UnitReport(unique_id),
  FOREIGN KEY (utility_id) REFERENCES Utility(utility_id)
);

-- ---------------------------------------------------------------------------
-- OccupancyHistory
-- `occupancy_or_vacancy_date_history` is the log description of occupancy.
-- Each history event belongs to one report and is stored as an atomic child row.
-- A range that ends before it starts is kept as filed; "reversed" is computed
-- as end_date < start_date rather than stored, since it follows from the dates.
-- ---------------------------------------------------------------------------
CREATE TABLE OccupancyHistory (
  history_id BIGINT AUTO_INCREMENT PRIMARY KEY,
  unique_id BIGINT NOT NULL,
  seq_no TINYINT UNSIGNED NOT NULL,
  range_type VARCHAR(40) NULL,
  start_date DATE NULL,
  end_date DATE NULL,
  UNIQUE (unique_id, seq_no),
  FOREIGN KEY (unique_id) REFERENCES UnitReport(unique_id)
);

-- ---------------------------------------------------------------------------
-- Data-quality problems are not stored in the database. Every source row is
-- loaded; a value that cannot be stored (for example a date in year 0001) is
-- set to NULL, and load_3nf.py writes each problem to quality_issues.csv
-- (unique_id, column, issue code, raw value, description). Rows are not
-- deleted: most problems are one disagreeing field on an otherwise valid
-- filing, and dropping those filings would bias the analysis.
-- ---------------------------------------------------------------------------

INSERT INTO FilingCycle VALUES
 (2022,'Housing Inventory - Unit information (2022)'),
 (2023,'Housing Inventory - Unit information (2023)'),
 (2024,'Housing Inventory - Unit information (2024)'),
 (2025,'Housing Inventory - Unit information (2025)'),
 (2026,'Housing Inventory - Unit information (2026)');

-- IDs are explicit because load_3nf.py mirrors them.
INSERT INTO OccupancyType(occupancy_type_id, name) VALUES
 (1,'Occupied by non-owner'), (2,'Vacant'), (3,'Occupied by owner'), (4,'Non-Residential');

INSERT INTO SupervisorDistrict(district_id)
 SELECT n FROM (SELECT 1 n UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4
 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8
 UNION ALL SELECT 9 UNION ALL SELECT 10 UNION ALL SELECT 11) d;

-- IDs 1-10 keep their original values; 11-16 were added for the wider
-- free-text patterns in clean_inventory.py.
INSERT INTO Utility(utility_id, name) VALUES
 (1,'water_sewer'), (2,'natural_gas'), (3,'electricity'), (4,'refuse_recycling'),
 (5,'heat'), (6,'internet'), (7,'parking'), (8,'storage'), (9,'pest_control'),
 (10,'other'), (11,'hot_water'), (12,'cable'), (13,'laundry'), (14,'janitorial'),
 (15,'solar'), (16,'all_utilities');
